import 'package:penta/model/notif.dart';
import 'package:penta/model/comment.dart';
import 'package:penta/model/post.dart';
import 'package:penta/model/user.dart';

//This data will get replaced by firebase in the future
final DUMMY_USERS = [
  User(
    id: 0,
    username: "elonmusk",
    email: "iamelon@gmail.com",
    name: "Elon Musk",
    photo:
        "https://i01.sozcucdn.com/wp-content/uploads/2021/03/11/iecrop/elonmusk-reuters_16_9_1615464321.jpg",
    bio: "Richest Man Alive",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 1,
    username: "jeffreyBezos",
    email: "bezosJeff@gmail.com",
    name: "Jeff Bezos",
    photo:
        "https://pbs.twimg.com/profile_images/669103856106668033/UF3cgUk4_400x400.jpg",
    bio: "Founder of Amazon",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 2,
    username: "harryP",
    email: "thepotter@gmail.com",
    name: "Harry Potter",
    photo:
        "https://imgrosetta.mynet.com.tr/file/14059491/14059491-728xauto.png",
    bio: "Yo, I know some magic!",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 3,
    username: "jMou",
    email: "josemourinho@gmail.com",
    name: "José Mourinho",
    photo:
        "https://iaaspr.tmgrup.com.tr/bf624c/414/262/0/0/2048/1299?u=https://iaspr.tmgrup.com.tr/2021/06/25/son-dakika-spor-haberi-roma-teknik-direktoru-jose-mourinho-milli-futbolcu-merih-demirali-istiyor-1624634491037.jpg",
    bio: "I am Jose Mourinho",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 4,
    username: "vfb1",
    email: "vfab@gmail.com",
    name: "Veysel Furkan Buruk",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Available for everyone!",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 5,
    username: "OfficialAyseNur",
    email: "aysecakmakofficial@gmail.com",
    name: "Ayse Nur Cakmak",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Like to have a private life",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 6,
    username: "ulmErg",
    email: "ulmerg@gmail.com",
    name: "Uluman Ergul",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "I am kind of a wolf man!",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 7,
    username: "JJmanager",
    email: "jesus@gmail.com",
    name: "Jorge Jesus",
    photo: "https://tele1.com.tr/wp-content/uploads/2022/05/jorge-690x450.jpg",
    bio: "Coach of the Fenerbahce Football Team",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 8,
    username: "erayelvan77",
    email: "erayelvan@gmail.com",
    name: "Eray Elvan",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Hi, I am using Penta!",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 9,
    username: "cankarsal",
    email: "cankarsal@gmail.com",
    name: "Can Karsal",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Future Electronic Engineer",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 10,
    username: "DemetMutlu",
    email: "demet1mutlu@gmail.com",
    name: "Demet Mutlu",
    photo: "https://cdn.karar.com/news/1384836.jpg",
    bio: "Entrepreneur!",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 11,
    username: "eloyazi",
    email: "eloya@gmail.com",
    name: "Ela Yazi",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "next gen AI Engineer",
    followers: Map(),
    following: Map(),
  ),
  User(
    id: 12,
    username: "erenbali",
    email: "erenbali@gmail.com",
    name: "Eren Bali",
    photo:
        "https://girisimturkiye.com/wp-content/uploads/2020/04/udemy-kurucu-orta%C4%9F%C4%B1-ve-ceosu-eren-bali.jpg",
    bio: "Co-founder of Udemy Academy",
    followers: Map(),
    following: Map(),
  ),
];

final DUMMY_POSTS = [
  Post(
    id: 0,
    username: "elonmusk",
    date: "22/05/2022",
    likes: 10,
    image: "assets/images/0.jpeg",
    location: "San Francisco",
    description: "It is good to relax after spending 22 billion dollar!!",
    comments: [
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "Am I the next one?",
        date: "22/05/2022",
        likes: 5,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 1,
    username: "jeffreyBezos",
    date: "30/05/2022",
    likes: 10,
    image: "assets/images/1.jpeg",
    location: "California",
    description: "Just took this amazing picture when I was jogging",
    comments: [
      Comment(
        userId: 2,
        username: "harryP",
        text: "It looks like some magic has been cast!!",
        date: "31/05/2022",
        likes: 1,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 2,
    username: "harryP",
    date: "29/05/2022",
    likes: 20,
    image: "assets/images/2.jpeg",
    location: "London, UK",
    description: "What an amazing place to try some spell.",
    comments: [
      Comment(
        userId: 2,
        username: "harryP",
        text: "Expecto Patronum!!!",
        date: "29/05/2022",
        likes: 1,
      ),
      Comment(
        userId: 3,
        username: "jMou",
        text: "It is unbelievable.",
        date: "30/05/2022",
        likes: 1,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 3,
    username: "jMou",
    date: "25/05/2022",
    likes: 10,
    image: "assets/images/3.jpeg",
    location: "Lisbon",
    description: "My favorite place after a season is over.",
    comments: [
      Comment(
        userId: 2,
        username: "harryP",
        text: "I hope, I will be there once.",
        date: "25/05/2022",
        likes: 4,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "This place is amazing.",
        date: "28/05/2022",
        likes: 1,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 4,
    username: "vfb1",
    date: "04/08/2022",
    likes: 10,
    image: "assets/images/4.jpeg",
    location: "Aokigahara",
    description: "Cannot stop thinking for a minute to dive into this lake.",
    comments: [
      Comment(
        userId: 2,
        username: "harryP",
        text: "Wow! Such an amazing photography.",
        date: "04/08/2022",
        likes: 7,
      ),
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "What a wonderful color this lake have.",
        date: "04/08/2022",
        likes: 4,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "Like this comment, I will bring you there",
        date: "04/08/2022",
        likes: 2,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 5,
    username: "OfficialAyseNur",
    date: "08/07/2022",
    likes: 10,
    image: "assets/images/5.jpeg",
    location: "Antalya",
    description: "An amazing experince thanks to suDosk.",
    comments: [
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "Spectacular",
        date: "08/07/2022",
        likes: 8,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "What a nice picture.",
        date: "08/07/2022",
        likes: 1,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 6,
    username: "ulmErg",
    date: "24/05/2022",
    likes: 10,
    image: "assets/images/6.jpeg",
    location: "Amazon Forest",
    description: "Hello! This is a photo that I took on my trip to Amazon.",
    comments: [
      Comment(
        userId: 5,
        username: "OfficialAyseNur",
        text: "That's the place that I want to be in.",
        date: "26/05/2022",
        likes: 3,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "Awesome",
        date: "26/05/2022",
        likes: 6,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 7,
    username: "JJmanager",
    date: "20/05/2022",
    likes: 10,
    image: "assets/images/7.jpeg",
    location: "Porto, Portugal",
    description: "Hello! I just agree the offer of Fenerbahce.",
    comments: [
      Comment(
        userId: 0,
        username: "elonmusk",
        text: "Welcome home",
        date: "20/05/2022",
        likes: 10,
      ),
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "Glad to see you on board.",
        date: "20/05/2022",
        likes: 10,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 8,
    username: "erayelvan77",
    date: "31/05/2022",
    likes: 10,
    image: "assets/images/8.jpeg",
    location: "Sile",
    description: "Dreaming about this.",
    comments: [
      Comment(
        userId: 0,
        username: "elonmusk",
        text: "Nice place to observe stars.",
        date: "01/06/2022",
        likes: 4,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "Eray, how did you go there?",
        date: "01/06/2022",
        likes: 1,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 9,
    username: "cankarsal",
    date: "07/07/2022",
    likes: 10,
    image: "assets/images/9.jpeg",
    location: "Konya Plain",
    description: "Feel like I am in a game.",
    comments: [
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "Actually, we are.",
        date: "08/07/2022",
        likes: 5,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "Amazing picture by a amateur photographer",
        date: "07/07/2022",
        likes: 3,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 10,
    username: "DemetMutlu",
    date: "05/06/2022",
    likes: 10,
    image: "assets/images/10.jpeg",
    location: "Argentina",
    description: "One of my favorite place I've ever been.",
    comments: [
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "What an entrepreneur minded.",
        date: "05/06/2022",
        likes: 1,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "One more lake that I want to dive added to the list.",
        date: "05/06/2022",
        likes: 1,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 11,
    username: "eloyazi",
    date: "01/06/2022",
    likes: 10,
    image: "assets/images/11.jpeg",
    location: "Polonezkoy",
    description: "This place inspired me to become an AI Engineer.",
    comments: [
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "Future CEO of Amazon maybe.",
        date: "02/06/2022",
        likes: 10,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "It's stunning.",
        date: "02/06/2022",
        likes: 4,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
  Post(
    id: 12,
    username: "erenbali",
    date: "22/05/2022",
    likes: 10,
    image: "assets/images/12.jpeg",
    location: "Arizona",
    description: "Hello! This is my first photo on Penta.",
    comments: [
      Comment(
        userId: 1,
        username: "jeffreyBezos",
        text: "I am everywhere.",
        date: "22/05/2022",
        likes: 7,
      ),
      Comment(
        userId: 4,
        username: "vfb1",
        text: "Welcome to app, boss.",
        date: "22/05/2022",
        likes: 4,
      ),
    ].toList(),
    topics: ["Nature", "Tree"],
  ),
];
final DUMMY_NOTIF = [
  Notif(
      userId: 1,
      username: "jeffreyBezos",
      text: "liked your photo",
      date: "1,1,1999",
      commentincl: true,
      postId: 12,
      activityId: 2),
  Notif(
      userId: 2,
      username: "harryP",
      text: "is following you",
      date: "1,1,1212",
      commentincl: false,
      postId: 12,
      activityId: 2),
  Notif(
      userId: 4,
      username: "vfb1",
      text: "commented on your photo",
      date: "1,1,1212",
      commentincl: true,
      postId: 10,
      activityId: 2),
  Notif(
      userId: 1,
      username: "jeffreyBezos",
      text: "sent you message",
      date: "1,1,1212",
      commentincl: false,
      postId: 12,
      activityId: 2),
  Notif(
      userId: 2,
      username: "harryP",
      text: "sent a new post",
      date: "1,1,1212",
      commentincl: true,
      postId: 4,
      activityId: 2),
];
