import 'package:penta/model/notif.dart';
import 'package:penta/model/comment.dart';
import 'package:penta/model/post.dart';
import 'package:penta/model/user.dart';

//This data will get replaced by firebase in the future
final DUMMY_USERS = [
  Profile(
    id: 0,
    username: "elonmusk",
    email: "iamelon@gmail.com",
    name: "Elon Musk",
    photo:
        "https://i01.sozcucdn.com/wp-content/uploads/2021/03/11/iecrop/elonmusk-reuters_16_9_1615464321.jpg",
    bio: "Richest Man Alive",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 1,
    username: "jeffreyBezos",
    email: "bezosJeff@gmail.com",
    name: "Jeff Bezos",
    photo:
        "https://pbs.twimg.com/profile_images/669103856106668033/UF3cgUk4_400x400.jpg",
    bio: "Founder of Amazon",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 2,
    username: "harryP",
    email: "thepotter@gmail.com",
    name: "Harry Potter",
    photo:
        "https://imgrosetta.mynet.com.tr/file/14059491/14059491-728xauto.png",
    bio: "Yo, I know some magic!",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 3,
    username: "jMou",
    email: "josemourinho@gmail.com",
    name: "José Mourinho",
    photo:
        "https://iaaspr.tmgrup.com.tr/bf624c/414/262/0/0/2048/1299?u=https://iaspr.tmgrup.com.tr/2021/06/25/son-dakika-spor-haberi-roma-teknik-direktoru-jose-mourinho-milli-futbolcu-merih-demirali-istiyor-1624634491037.jpg",
    bio: "I am Jose Mourinho",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 4,
    username: "vfb1",
    email: "vfab@gmail.com",
    name: "Veysel Furkan Buruk",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Available for everyone!",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 5,
    username: "OfficialAyseNur",
    email: "aysecakmakofficial@gmail.com",
    name: "Ayse Nur Cakmak",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Like to have a private life",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 6,
    username: "ulmErg",
    email: "ulmerg@gmail.com",
    name: "Uluman Ergul",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "I am kind of a wolf man!",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 7,
    username: "JJmanager",
    email: "jesus@gmail.com",
    name: "Jorge Jesus",
    photo: "https://tele1.com.tr/wp-content/uploads/2022/05/jorge-690x450.jpg",
    bio: "Coach of the Fenerbahce Football Team",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 8,
    username: "erayelvan77",
    email: "erayelvan@gmail.com",
    name: "Eray Elvan",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Hi, I am using Penta!",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 9,
    username: "cankarsal",
    email: "cankarsal@gmail.com",
    name: "Can Karsal",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "Future Electronic Engineer",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 10,
    username: "DemetMutlu",
    email: "demet1mutlu@gmail.com",
    name: "Demet Mutlu",
    photo: "https://cdn.karar.com/news/1384836.jpg",
    bio: "Entrepreneur!",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 11,
    username: "eloyazi",
    email: "eloya@gmail.com",
    name: "Ela Yazi",
    photo: "https://icon-library.com/images/profile-icon/profile-icon-22.jpg",
    bio: "next gen AI Engineer",
    followers: Map(),
    following: Map(),
  ),
  Profile(
    id: 12,
    username: "erenbali",
    email: "erenbali@gmail.com",
    name: "Eren Bali",
    photo:
        "https://girisimturkiye.com/wp-content/uploads/2020/04/udemy-kurucu-orta%C4%9F%C4%B1-ve-ceosu-eren-bali.jpg",
    bio: "Co-founder of Udemy Academy",
    followers: Map(),
    following: Map(),
  ),
];

final DUMMY_POSTS = [
  Post(
    mediaUrl: "https://pbs.twimg.com/media/E9YJOcmWQAczMrY.jpg",
    username: "elonmusk",
    location: "San Fransisco",
    description: "It is good to relax after spending 22 billion dollars!",
    likes: 10,
    postId: "0",
    ownerId: "0",
  ),
];
final DUMMY_NOTIF = [
  Notif(
      userId: 1,
      username: "jeffreyBezos",
      text: "liked your photo",
      date: "1,1,1999",
      commentincl: true,
      postId: 12,
      activityId: 2),
  Notif(
      userId: 2,
      username: "harryP",
      text: "is following you",
      date: "1,1,1212",
      commentincl: false,
      postId: 12,
      activityId: 2),
  Notif(
      userId: 4,
      username: "vfb1",
      text: "commented on your photo",
      date: "1,1,1212",
      commentincl: true,
      postId: 10,
      activityId: 2),
  Notif(
      userId: 1,
      username: "jeffreyBezos",
      text: "sent you message",
      date: "1,1,1212",
      commentincl: false,
      postId: 12,
      activityId: 2),
  Notif(
      userId: 2,
      username: "harryP",
      text: "sent a new post",
      date: "1,1,1212",
      commentincl: true,
      postId: 4,
      activityId: 2),
];
